apiVersion: v1
kind: Service
metadata:
  name: cortex-backend
  namespace: cortex-gateway
  labels:
    app.kubernetes.io/name: cortex-gateway
    app.kubernetes.io/component: backend
spec:
  selector:
    app: cortex-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
